### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [hpfxd/SpectatorPlus#10]

**Comment by letsgoawaydev** [comment]
bump

**Comment by hpfxd** [comment]
[SpectatorPlus 1.2.1 for Minecraft 1.21 has been released!](https://modrinth.com/plugin/spectatorplus/version/fabric-1.2.1+mc1.21) :)

**Comment by venaminecraft** [comment]
Thank you 😄

**Comment by letsgoawaydev** [comment]
nice :)
